spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: demo
    password: demo
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093, localhost:9094
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: transactions-listener-group
      fetch-min-size: 1024
      fetch-max-wait: 500
      max-poll-records: 500
      properties:

        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.kafkaconsumer.entity.Transaction
      listener:
        ack-mode: MANUAL_IMMEDIATE
      auto-offset-reset: earliest